-- Dump of girls (12 rows)
-- Source: Secretstory Turso DB
-- Date: 2026-05-09T12:09:17.078Z

-- Original schema (for reference):
-- CREATE TABLE girls (
--   id INTEGER PRIMARY KEY AUTOINCREMENT,
--   name TEXT NOT NULL,
--   slug TEXT NOT NULL UNIQUE,
--   email TEXT,
--   phone TEXT,
--   age INTEGER,
--   nationality TEXT,
--   height INTEGER,
--   weight INTEGER,
--   bust TEXT,
--   hair TEXT,
--   eyes TEXT,
--   color TEXT,
--   status TEXT DEFAULT 'pending' CHECK(status IN ('active', 'pending', 'inactive')),
--   verified BOOLEAN DEFAULT 0,
--   online BOOLEAN DEFAULT 0,
--   rating REAL DEFAULT 0,
--   reviews_count INTEGER DEFAULT 0,
--   bookings_count INTEGER DEFAULT 0,
--   services TEXT,
--   bio TEXT,
--   created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
--   updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
-- , tattoo_percentage INTEGER DEFAULT 0, tattoo_description TEXT, piercing INTEGER DEFAULT 0, piercing_description TEXT, languages TEXT, schedule TEXT, description_cs TEXT, description_en TEXT, description_de TEXT, description_uk TEXT, location TEXT, photos TEXT, is_new BOOLEAN DEFAULT 0, is_top BOOLEAN DEFAULT 0, is_featured BOOLEAN DEFAULT 0, featured_section TEXT, badge_type TEXT, meta_title TEXT DEFAULT NULL, meta_description TEXT DEFAULT NULL, og_image TEXT DEFAULT NULL, hashtags TEXT, tattoo_description_cs TEXT, tattoo_description_en TEXT, tattoo_description_de TEXT, tattoo_description_uk TEXT, piercing_description_cs TEXT, piercing_description_en TEXT, piercing_description_de TEXT, piercing_description_uk TEXT, og_description TEXT, og_title TEXT, bio_cs TEXT, bio_de TEXT, bio_uk TEXT, meta_title_cs TEXT, meta_title_en TEXT, meta_title_de TEXT, meta_title_uk TEXT, meta_description_cs TEXT, meta_description_en TEXT, meta_description_de TEXT, meta_description_uk TEXT, og_title_cs TEXT, og_title_en TEXT, og_title_de TEXT, og_title_uk TEXT, og_description_cs TEXT, og_description_en TEXT, og_description_de TEXT, og_description_uk TEXT, subtitle_cs TEXT, subtitle_en TEXT, subtitle_de TEXT, subtitle_uk TEXT)

DROP TABLE IF EXISTS "girls";
CREATE TABLE girls (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  email TEXT,
  phone TEXT,
  age INTEGER,
  nationality TEXT,
  height INTEGER,
  weight INTEGER,
  bust TEXT,
  hair TEXT,
  eyes TEXT,
  color TEXT,
  status TEXT DEFAULT 'pending' CHECK(status IN ('active', 'pending', 'inactive')),
  verified BOOLEAN DEFAULT 0,
  online BOOLEAN DEFAULT 0,
  rating REAL DEFAULT 0,
  reviews_count INTEGER DEFAULT 0,
  bookings_count INTEGER DEFAULT 0,
  services TEXT,
  bio TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
, tattoo_percentage INTEGER DEFAULT 0, tattoo_description TEXT, piercing INTEGER DEFAULT 0, piercing_description TEXT, languages TEXT, schedule TEXT, description_cs TEXT, description_en TEXT, description_de TEXT, description_uk TEXT, location TEXT, photos TEXT, is_new BOOLEAN DEFAULT 0, is_top BOOLEAN DEFAULT 0, is_featured BOOLEAN DEFAULT 0, featured_section TEXT, badge_type TEXT, meta_title TEXT DEFAULT NULL, meta_description TEXT DEFAULT NULL, og_image TEXT DEFAULT NULL, hashtags TEXT, tattoo_description_cs TEXT, tattoo_description_en TEXT, tattoo_description_de TEXT, tattoo_description_uk TEXT, piercing_description_cs TEXT, piercing_description_en TEXT, piercing_description_de TEXT, piercing_description_uk TEXT, og_description TEXT, og_title TEXT, bio_cs TEXT, bio_de TEXT, bio_uk TEXT, meta_title_cs TEXT, meta_title_en TEXT, meta_title_de TEXT, meta_title_uk TEXT, meta_description_cs TEXT, meta_description_en TEXT, meta_description_de TEXT, meta_description_uk TEXT, og_title_cs TEXT, og_title_en TEXT, og_title_de TEXT, og_title_uk TEXT, og_description_cs TEXT, og_description_en TEXT, og_description_de TEXT, og_description_uk TEXT, subtitle_cs TEXT, subtitle_en TEXT, subtitle_de TEXT, subtitle_uk TEXT);

INSERT INTO "girls" ("id", "name", "slug", "email", "phone", "age", "nationality", "height", "weight", "bust", "hair", "eyes", "color", "status", "verified", "online", "rating", "reviews_count", "bookings_count", "services", "bio", "created_at", "updated_at", "tattoo_percentage", "tattoo_description", "piercing", "piercing_description", "languages", "schedule", "description_cs", "description_en", "description_de", "description_uk", "location", "photos", "is_new", "is_top", "is_featured", "featured_section", "badge_type", "meta_title", "meta_description", "og_image", "hashtags", "tattoo_description_cs", "tattoo_description_en", "tattoo_description_de", "tattoo_description_uk", "piercing_description_cs", "piercing_description_en", "piercing_description_de", "piercing_description_uk", "og_description", "og_title", "bio_cs", "bio_de", "bio_uk", "meta_title_cs", "meta_title_en", "meta_title_de", "meta_title_uk", "meta_description_cs", "meta_description_en", "meta_description_de", "meta_description_uk", "og_title_cs", "og_title_en", "og_title_de", "og_title_uk", "og_description_cs", "og_description_en", "og_description_de", "og_description_uk", "subtitle_cs", "subtitle_en", "subtitle_de", "subtitle_uk") VALUES
(20, 'Sara', 'sara', 'u6907820408@gmail.com', '+420734332131', 29, 'Česká', 154, 45, '2', 'Hnědé', 'Hnědé', '#e91e63', 'active', 0, 0, 4.857142857142857, 7, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","hard_sex","light_sm","role_play","threesome_mfm","blowjob_no_condom","deepthroat","cof"]', '', '2025-12-26 08:10:26', '2026-02-14 14:33:31', 10, 'Malé tetování', 1, 'v pupíku', '["cs","en"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 0, 0, 0, '', '', '', '', '', '["brunetky-praha","prirodni-poprsi","plne-rty","tetovani","piercing-holky","stihla-postava","mlade-holky","holky-praha","spolecnice-praha","gfe-praha"]', '', '', '', '', '', '', '', '', '', '', '', '', '', 'Test SEO CS Title - 2026-01-01T20:09:25.216Z', 'Test SEO EN Title - 2026-01-01T20:09:25.217Z', '', '', 'Test description CS', '', '', '', 'Test OG Title CS', '', '', '', '', '', '', '', '', '', '', ''),
(21, 'Elizabeth', 'elizabeth', 'ngasparovicova@seznam.cz', '+420734332131', 22, 'Česká', 170, 61, '2', 'Blond', 'Modré', '#2196f3', 'active', 0, 0, 0, 0, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","prostate_massage","hard_sex","light_sm","facesitting","foot_fetish","bdsm","role_play","bondage","threesome_fmf","threesome_mfm","kissing","blowjob_no_condom","deepthroat","cof","cim","swallow","anal_girl","anal_man","rimming_active","rimming_passive","piss_passive","filming_face","filming_no_face"]', 'Elizabeth steps in softly: half a step closer, warm nape touch, and the noise drops. She starts gentle and, on your cue, tightens the line—kissing that lingers, a pace laid exactly where the spark should land. She enjoys kissing, deeper oral, facesitting and foot fetish; by agreement she adds role-play, light bondage, soft-edge BDSM and rimming (active/passive). Everything is discreet, safe and clearly consented, with hygiene and boundaries.', '2025-12-26 08:16:24', '2026-01-15 09:23:30', 0, '', 0, '', '["cs","en"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 0, 0, 0, '', '', '', '', '', '["blondynky-praha","prirodni-poprsi","krivky","studentky-praha","ceske-holky","holky-praha","spolecnice-praha","mlade-holky"]', '', '', '', '', '', '', '', '', '', '', 'Elizabeth přichází potichu: půl krok blíž, teplo na šíji a pohled, co vypne šum v hlavě. Začne něžně, ale na znamení přidá přesnost—polibky zjemní i prohloubí, tempo srovná přesně tam, kde chceš cítit jiskru.
Má ráda líbání, hlubší orální hru, facesitting a foot fetish; po dohodě přidá role-play, svazování, jemnější BDSM a rimming (aktiv/pasiv). Všechno je domluvené, diskrétní a bezpečné, s jasnými hranicemi a hygienou.', 'Elizabeth öffnet leise: halber Schritt, warmes Nacken-Touch, und der Raum wird still. Sanft im Einstieg, präziser auf dein Zeichen—Küsse werden tiefer, das Tempo sitzt genau dort, wo der Funke landen soll. Sie liebt Küssen, intensiveres Oralespiel, Facesitting und Fußfetisch; nach Absprache kommen Role-Play, Bondage, softes BDSM und Rimming (aktiv/passiv) dazu. Sauber verabredet, diskret und sicher, mit Hygiene und klaren Grenzen.', 'Elizabeth входить тихо: пів кроку ближче, тепла рука на потилиці — і кімната стихає. Ніжний старт, точніше на знак: поцілунки затримуються довше, ритм лягає саме туди, де має спалахнути іскра. За домовленістю вона додасть роль-плей, легкий бондаж, м’яке BDSM і ріммінг (актив/пасив). Усе узгоджено, конфіденційно та безпечно; гігієна і межі — без варіантів.', 'Elizabeth – smyslná blondýnka Praha, křivky ✨! | LovelyGirls', 'Elizabeth – Prague blonde, curves and heat ✨!. | LovelyGirls', 'Elizabeth – Blonde Begleiterin Prag, Kurven ✨! | LovelyGirls', 'Elizabeth – блондинка у Празі, ніжні вигини ✨! | LovelyGirls', 'Mladá blondýnka s křivkami. Líbání, hlubší orál, facesitting a foot fetish; role-play, svazování, BDSM a rimming po dohodě. Diskrétně, bezpečně, s hranicemi.', 'Young blonde with curves. Kissing, deep oral, facesitting and foot fetish; role-play, bondage, BDSM and rimming by agreement. Discreet, safe, firm boundaries.', 'Junge Blonde mit Kurven. Küssen, Deep-Oral, Facesitting und Fußfetisch; Role-Play, Bondage, BDSM und Rimming nach Absprache. Diskret, sicher, klare Grenzen.', 'Молода блондинка з вигинами. Поцілунки, deep-oral, фейссіттінг і фут-фетиш; роль-плей, бондаж і ріммінг — за домовленістю. Конфіденційно, безпечно, чіткі межі.', 'Elizabeth – smyslná blondýnka Praha, křivky ✨! | LovelyGirls', 'Elizabeth – Prague blonde, curves and heat ✨!. | LovelyGirls', 'Elizabeth – Blonde Begleiterin Prag, Kurven ✨! | LovelyGirls', 'Elizabeth – блондинка у Празі, ніжні вигини ✨! | LovelyGirls', 'Mladá blondýnka s křivkami. Líbání, hlubší orál, facesitting a foot fetish; role-play, svazování, BDSM a rimming po dohodě. Diskrétně, bezpečně, s hranicemi.', 'Young blonde with curves. Kissing, deep oral, facesitting and foot fetish; role-play, bondage, BDSM and rimming by agreement. Discreet, safe, firm boundaries.', 'Junge Blonde mit Kurven. Küssen, Deep-Oral, Facesitting und Fußfetisch; Role-Play, Bondage, BDSM und Rimming nach Absprache. Diskret, sicher, klare Grenzen.', 'Молода блондинка з вигинами. Поцілунки, deep-oral, фейссіттінг і фут-фетиш; роль-плей, бондаж і ріммінг — за домовленістю. Конфіденційно, безпечно, чіткі межі.', 'Křivky, co si řeknou o vedení 🎯', 'Curves that ask for cadence ✨', 'Kurven mit feiner Führung 💎', 'Вигини, що просять ритму 🌙'),
(22, 'Luna', 'luna', 'u3911680787@gmail.com', '+420734332131', 19, 'Česká', 167, 50, '3', 'Hnědé', 'Hnědé', '#ff9800', 'active', 0, 0, 5, 8, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","prostate_massage","hard_sex","light_sm","facesitting","foot_fetish","lesbi_show","bondage","threesome_mfm","kissing","blowjob_no_condom","deepthroat","cof","cim","swallow","piss_active"]', '', '2025-12-26 08:20:01', '2026-04-16 14:57:57', 60, 'Ruce, Nohy, Tělo', 0, '', '["cs","en"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 0, 0, 0, '', '', '', '', '', '["brunetky-praha","prirodni-poprsi","dlouhe-nohy","plne-rty","tetovani","piercing-holky","fit-holky","stihla-postava","mlade-holky","studentky-praha","holky-praha","spolecnice-praha","girlfriend-experience","gfe-praha"]', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(25, 'Nika', 'nika', 'vve.veruska@gmail.com', '+420734332131', 28, 'Česká', 162, 50, '2', 'Blond', 'Modré', '#00bcd4', 'active', 0, 0, 5, 26, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","prostate_massage","hard_sex","light_sm","facesitting","foot_fetish","bdsm","lesbi_show","role_play","bondage","threesome_fmf","threesome_mfm","kissing","blowjob_no_condom","deepthroat","cof","cim","swallow","anal_girl","anal_man","piss_passive"]', '', '2025-12-28 11:32:04', '2026-03-13 12:27:57', 40, 'Ruce, nohy.', 0, '', '["cs","en"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 0, 0, 0, '', '', '', '', '', '["blondynky-praha","prirodni-poprsi","dlouhe-nohy","plne-rty","kratke-vlasy","tetovani","piercing-holky","stihla-postava","milf-praha","ceske-holky","gfe-praha","girlfriend-experience","spolecnice-praha","holky-praha"]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(26, 'Natalie', 'natalie', 'naty123@naty.cz', '+420734332131', 23, 'Česká', 170, 63, '4', 'Blond', 'Modré', '#f44336', 'active', 0, 0, 5, 1, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","prostate_massage","hard_sex","light_sm","facesitting","foot_fetish","lesbi_show","role_play","kissing","blowjob_no_condom","deepthroat","cof","cim","swallow","piss_passive"]', '', '2025-12-28 13:10:59', '2026-05-06 07:26:47', 15, 'Malé tetování na zádech', 0, '', '["cs","en"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 0, 0, 0, '', '', '', '', '', '[]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', NULL, NULL, NULL, NULL),
(27, 'Rebeca', 'rebeca', 'janca.lucky@gmail.com', '+420734332131', 30, 'Česká', 176, 63, '1', 'Černé', 'Hnědé', '#ffeb3b', 'active', 0, 0, 5, 1, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","hard_sex","light_sm","facesitting","foot_fetish","role_play","lesbi_show","threesome_fmf","threesome_mfm","kissing","blowjob_no_condom","anal_man","filming_face","filming_no_face"]', '', '2025-12-28 13:18:46', '2026-02-14 14:34:14', 50, 'Hodně tetování, ruce, nohy, tělo.', 0, '', '["cs","en"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 0, 0, 0, '', '', '', '', '', '["cernovlasky-praha","prirodni-poprsi","plne-rty","fit-holky","tetovani","piercing-holky","ceske-holky","gfe-praha","girlfriend-experience","holky-praha","spolecnice-praha"]', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(28, 'Emily', 'emily', 'katerina.capkov@gmail.com', '+420734332131', 20, 'Česká', 176, 60, '2', 'Blond', 'Modré', '#673ab7', 'active', 0, 0, 5, 8, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","hard_sex","light_sm","facesitting","foot_fetish","role_play","kissing","blowjob_no_condom","cof","cim","swallow","piss_active"]', 'Emily přichází v klidu: půl krok blíž, oči drží kontakt o vteřinu déle a svět ztichne. Vnímá tvoje signály a z něhy plynule přepíná do přesnější hry ve chvíli, kdy kývneš. Její styl je kultivovaný, lidský a jistý—proto od ní lidé odcházejí s klidem i žárem.
Ráda líbá a jde do hlubší orální hry; po dohodě přidá role-play a rimming (aktiv/pasiv). Všechno je čistě domluvené, bezpečné a diskrétní, s důrazem na hygienu a jasné hranice. Hledáš GFE, které nepůsobí jako šablona, ale skutečně dýchá? Tady je.', '2025-12-28 13:22:45', '2026-04-15 15:25:21', 0, '', 0, '', '["cs","en"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 0, 0, 0, '', '', '', '', '', '["blondynky-praha","prirodni-poprsi","plne-rty","dlouhe-nohy","mlade-holky","studentky-praha","ceske-holky","holky-praha","spolecnice-praha","gfe-praha","girlfriend-experience"]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', 'Emily přichází v klidu: půl krok blíž, oči drží kontakt o vteřinu déle a svět ztichne. Vnímá tvoje signály a z něhy plynule přepíná do přesnější hry ve chvíli, kdy kývneš. Její styl je kultivovaný, lidský a jistý—proto od ní lidé odcházejí s klidem i žárem.
Ráda líbá a jde do hlubší orální hry; po dohodě přidá role-play a rimming (aktiv/pasiv). Všechno je čistě domluvené, bezpečné a diskrétní, s důrazem na hygienu a jasné hranice. Hledáš GFE, které nepůsobí jako šablona, ale skutečně dýchá? Tady je.', 'Emily öffnet leise: halber Schritt, ruhiger Blick, das Rauschen wird still. Sie liest deine Signale und dosiert präziser, sobald du nickst—kultiviert, menschlich, verlässlich. Deshalb bleiben ihre Treffen im Kopf: warm, klar und elegant.
Sie liebt Küssen und intensiveres Oralespiel; Role-Play und Rimming (aktiv/passiv) gibt es nur nach Absprache. Alles sauber vereinbart, diskret und sicher, mit Hygiene und klaren Grenzen.', 'Emily přichází v klidu: půl krok blíž, oči drží kontakt o vteřinu déle a svět ztichne. Vnímá tvoje signály a z něhy plynule přepíná do přesnější hry ve chvíli, kdy kývneš. Její styl je kultivovaný, lidský a jistý—proto od ní lidé odcházejí s klidem i žárem.
Ráda líbá a jde do hlubší orální hry; po dohodě přidá role-play a rimming (aktiv/pasiv). Všechno je čistě domluvené, bezpečné a diskrétní, s důrazem na hygienu a jasné hranice. Hledáš GFE, které nepůsobí jako šablona, ale skutečně dýchá? Tady je.', 'Emily – elitní společnice Praha, top přístup ✨ | LovelyGirls', 'Emily – Prague companion, refined & warm ✨ now | LovelyGirls', 'Emily – Begleiterin Prag, elegante Attitüde ✨! | LovelyGirls', '', 'Top v hodnocení i chování. Líbání, hlubší orální hra, role-play a rimming po dohodě—vždy diskrétně, bezpečně a s jasnými hranicemi. Chemie, co drží. Důvěra.', 'Top in reviews and manners. Kissing, deep oral, role-play and rimming by agreement—discreet, safe, clearly consented with firm boundaries. Chemistry that stays.', 'Top bei Bewertungen und Verhalten. Küssen, Deep-Oral, Role-Play und Rimming nach Absprache—diskret, sicher und mit klaren Grenzen. Chemie, die bleibt.', '', 'Emily – elitní společnice Praha, top přístup ✨ | LovelyGirls', 'Emily – Prague companion, refined & warm ✨ now | LovelyGirls', 'Emily – Begleiterin Prag, elegante Attitüde ✨! | LovelyGirls', '', 'Top v hodnocení i chování. Líbání, hlubší orální hra, role-play a rimming po dohodě—vždy diskrétně, bezpečně a s jasnými hranicemi. Chemie, co drží. Důvěra.', 'Top in reviews and manners. Kissing, deep oral, role-play and rimming by agreement—discreet, safe, clearly consented with firm boundaries. Chemistry that stays.', 'Top bei Bewertungen und Verhalten. Küssen, Deep-Oral, Role-Play und Rimming nach Absprache—diskret, sicher und mit klaren Grenzen. Chemie, die bleibt.', '', 'Top hodnocení, lidský dotek 🖤', 'Top reviews, human warmth ✨', 'Top-Bewertungen, feine Wärme 💎', ''),
(31, 'Katy', 'katy', 'caty22387@gmail.com', '+420734332131', 21, 'Česká', 155, 47, '2', 'Hnědé', 'Modré', '#3f51b5', 'active', 0, 0, 4.166666666666667, 18, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","prostate_massage","hard_sex","light_sm","facesitting","foot_fetish","bdsm","lesbi_show","role_play","bondage","threesome_fmf","threesome_mfm","deepthroat","cof","rimming_passive","rimming_active","piss_active","piss_passive"]', '', '2025-12-29 05:43:23', '2026-03-11 14:53:34', 15, 'Malé tetování na těle', 0, '', '["cs","en"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 0, 0, 0, '', '', '', '', '', '["blondynky-praha","prirodni-poprsi","plne-rty","stihla-postava","mlade-holky","holky-praha","spolecnice-praha","ceske-holky"]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '', '', 'Katy je drobná, lehká na dotek a přesná v načasování. Začne něžně—úsměv, půl krok blíž, dech na šíji—a když kývneš, přidá tlak, tempo i vedení. Chemie má u ní tvar, ne hluk.
Miluje líbání a hlubší orální hru, umí být sub i drzá provokatérka. Facesitting, foot fetish, role-play, svazování a BDSM zapojí po dohodě; rimming (aktiv/pasiv), piss a trojky drží v čistém, bezpečném rámci. Diskrétnost, hygiena a respekt jsou samozřejmost.
', 'Katy öffnet leise: Lächeln, halber Schritt, warme Nackenhand. Auf dein Nicken zieht sie die Linie fester—Tempo, Druck, Führung. Gefühl mit Form statt Theater.
Sie liebt Küssen und intensiveres Oralespiel; kann sub oder frech führen. Facesitting, Fußfetisch, Role-Play, Bondage und BDSM nur nach Absprache; Rimming (aktiv/passiv), Piss und Dreier bleiben sauber gerahmt. Diskretion, Hygiene und Respekt sind gesetzt.', '', 'Katy – perverzní společnice Praha, malý ďábel⚡ | LovelyGirls', '', 'Katy – perverse Begleiterin Prag, frech klein⚡ | LovelyGirls', '', 'Jemná na začátek, drzejší na znamení. Líbání, orál, facesitting, foot fetish, role-play, svazování a rimming—vždy diskrétně, bezpečně s jasnými hranicemi.', '', 'Zarter Einstieg, frecher auf Zeichen: Küssen, Deep-Oral, Facesitting, Fußfetisch, Role-Play, Bondage und Rimming—diskret, sicher, klare Grenzen, Hygiene.', '', 'Katy – perverzní společnice Praha, malý ďábel⚡ | LovelyGirls', '', 'Katy – perverse Begleiterin Prag, frech klein⚡ | LovelyGirls', '', 'Jemná na začátek, drzejší na znamení. Líbání, orál, facesitting, foot fetish, role-play, svazování a rimming—vždy diskrétně, bezpečně s jasnými hranicemi.', '', 'Zarter Einstieg, frecher auf Zeichen: Küssen, Deep-Oral, Facesitting, Fußfetisch, Role-Play, Bondage und Rimming—diskret, sicher, klare Grenzen, Hygiene.', '', 'Malá výška, velké jiskry 🔥', 'Small frame, big voltage 💥', 'Klein im Maß, groß im Feuer ⚡', 'Малий зріст, велика напруга 🎯'),
(41, 'Anetta', 'anetta', 'anetta@gmail.com', '+420734332131', 19, 'Slovenka', 165, 50, '1', 'Černé', 'Zelené', '#9c27b0', 'active', 0, 0, 3, 1, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","foot_fetish","kissing","blowjob_no_condom"]', 'Anetta feels calm and a little cold—exactly the kind of tension that pulls you in. She doesn’t overtalk it: you lead, she follows your tone and responds with precision. When your guidance is clear, the softness turns into a focused spark.
She loves kissing. Foot fetish and oral without a condom are by agreement only, kept clean, discreet and safe, with firm boundaries and hygiene first.
', '2026-04-02 18:15:29', '2026-04-26 08:30:33', 0, '', 0, '', '["en","cs"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 1, 0, 0, 'homepage_new', 'new', '', '', '', '["cernovlasky-praha","prirodni-poprsi","plne-rty","fit-holky","stihla-postava","mlade-holky","studentky-praha","holky-praha","spolecnice-praha","gfe-praha","sexy-holky","krasne-holky","hot-holky-praha","dokonale-telo"]', '', '', '', '', '', '', '', '', '', '', 'Anetta je mladá a působí trochu chladně—právě to ale dělá tu jiskru. Nehraje to na přehnané řeči: přijde blíž, nechá tě převzít vedení a reaguje přesně na tón, který nastavíš. Když ji vedeš jistě, z jemnosti se stane velmi konkrétní napětí.
Miluje líbání, vnímá detaily a nechá si líbit, když máš jasný směr. Foot fetish a orál bez kondomu jsou jen po dohodě, vždy v čistém a bezpečném rámci s jasnými hranicemi. Diskrétnost a hygiena jsou samozřejmost.', 'Anetta wirkt ruhig und etwas kühl—und genau das macht den Reiz. Sie braucht kein Theater: du führst, sie reagiert. Wenn du klar bist, wird aus der Sanftheit ein präziser, spannender Rhythmus.
Küssen liebt sie sehr; Fußfetisch und Oral ohne Kondom gibt es nur nach Absprache, sauber und sicher gerahmt. Diskretion, Hygiene und klare Grenzen sind gesetzt.', 'Anetta здається спокійною й трохи холодною—і саме це створює напругу. Вона не грає словами: ти ведеш, вона підлаштовується під твій тон і відповідає точно. Коли ведення впевнене, ніжність стає дуже прицільною.
Вона любить поцілунки. Фут-фетиш і орал без презерватива — лише за домовленістю, у чистому, безпечному форматі. Дискретність, гігієна та межі — обов’язково.', 'Anetta – mladá Praha, jemná a pod vedením ✨19! | LovelyGirls', 'Anetta – Prague, soft and loves your lead ✨19! | LovelyGirls', 'Anetta – jung in Prag, sanft & gern geführt ✨19| LovelyGirls', 'Anetta – Праза, ніжна й любить твоє ведення ✨19| LovelyGirls', 'Mladá a jemná, trochu chladná—miluje, když muž vede. Líbání, foot fetish a orál bez kondomu po dohodě; vše diskrétně, bezpečně, s jasnými hranicemi.', 'Young, soft, a little cold—she loves a man who leads. Kissing, foot fetish and oral without condom by agreement; discreet, safe, with clear boundaries and hygie', 'Jung, sanft, leicht kühl—sie liebt klare Führung. Küssen, Fußfetisch und Oral ohne Kondom nach Absprache; diskret, sicher, mit Grenzen und Hygiene.', 'Молода, ніжна, трохи холодна—любить, коли чоловік веде. Поцілунки, фут-фетиш і орал без презерватива за домовленістю; конфіденційно, безпечно, межі й гігієна.', 'Anetta – mladá Praha, jemná a pod vedením ✨19! | LovelyGirls', 'Anetta – Prague, soft and loves your lead ✨19! | LovelyGirls', 'Anetta – jung in Prag, sanft & gern geführt ✨19| LovelyGirls', 'Anetta – Праза, ніжна й любить твоє ведення ✨19| LovelyGirls', 'Mladá a jemná, trochu chladná—miluje, když muž vede. Líbání, foot fetish a orál bez kondomu po dohodě; vše diskrétně, bezpečně, s jasnými hranicemi.', 'Young, soft, a little cold—she loves a man who leads. Kissing, foot fetish and oral without condom by agreement; discreet, safe, with clear boundaries and hygie', 'Jung, sanft, leicht kühl—sie liebt klare Führung. Küssen, Fußfetisch und Oral ohne Kondom nach Absprache; diskret, sicher, mit Grenzen und Hygiene.', 'Молода, ніжна, трохи холодна—любить, коли чоловік веде. Поцілунки, фут-фетиш і орал без презерватива за домовленістю; конфіденційно, безпечно, межі й гігієна.', 'Jemná, chladná, pod tvým vedením 🖤', 'Soft touch, colder tease 💫', 'Sanft, kühl, auf dein Signal 🎯', 'Ніжність і контроль 🌙'),
(42, 'Dana', 'dana', 'dana123@seznam.cz', '+420734332131', 28, 'Ukrajinka', 160, 60, '3', 'Hnědé', 'Modré', '#009688', 'active', 0, 0, 0, 0, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","light_sm","foot_fetish","kissing","blowjob_no_condom","cof","cim"]', NULL, '2026-04-05 05:48:42', '2026-04-05 05:49:02', 0, NULL, 0, NULL, '["cs","en","uk","ru"]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 'homepage_new', 'new', NULL, NULL, NULL, '["brunetky-praha","prirodni-poprsi","velka-prsa","krivky","ukrajinske-holky","holky-praha","spolecnice-praha","girlfriend-experience","gfe-praha","modre-oci"]', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(43, 'Lyra', 'lyra', 'lyra123@seznam.cz', '+420734332131', 25, 'Jiná', 169, 50, '1', 'Černé', 'Hnědé', '#ff5722', 'active', 0, 0, 0, 0, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","foot_fetish","kissing","deepthroat","facesitting","threesome_mfm","rimming_passive","piss_passive"]', '', '2026-04-07 16:09:52', '2026-04-08 07:18:47', 0, '', 0, '', '["en"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 1, 0, 0, 'homepage_new', 'new', '', '', '', '["cernovlasky-praha","prirodni-poprsi","dlouhe-nohy","fit-holky","stihla-postava","studentky-praha","exoticke-krasky","holky-praha","spolecnice-praha","sexy-holky","gfe-praha","girlfriend-experience","krasne-holky","hot-holky-praha","luxusni-sluzby","elegantni-holky","dlouhe-vlasy"]', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(44, 'Eliška', 'eliska', 'eliska@gmail.com', '+420734332131', 27, 'Ruska', 168, 65, '2', 'Blond', 'Zelené', '#8bc34a', 'active', 0, 0, 0, 0, 0, '["classic","blowjob_condom","massage","cuddling","licking","69","cum_on_body","shared_shower","erotic_massage","light_sm","threesome_mfm","foot_fetish","deepthroat","role_play"]', '', '2026-04-21 06:46:53', '2026-04-22 07:13:51', 40, 'stehna, ruce, male tetovaní na zádech.', 0, '', '["cs","en","uk","ru"]', NULL, NULL, NULL, NULL, NULL, 'Praha 2', NULL, 1, 0, 0, 'homepage_new', 'new', '', '', '', '["blondynky-praha","prirodni-poprsi","tetovani","krivky","mlade-holky","ruske-holky","ukrajinske-holky","holky-praha","spolecnice-praha"]', '', '', '', '', '', '', '', '', '', '', 'Eliška je moc příjemná blondýnka, co umí udělat atmosféru bez velkých řečí. Přijde potichu, nechá tě vydechnout a dotekem na šíji vypne šum v hlavě. Když jí dáš signál, přidá přesnost—tempo se srovná, vedení je jistější a chemie začne pracovat sama.
Miluje hlubší orální hru, ráda si pohraje s foot fetishem. Role-play a lehké SM přidá jen po dohodě, stejně jako MŽM trojku—vždy v čistém, bezpečném rámci s jasnými hranicemi. Mluví CS/EN/UK/RU, diskrétnost a hygiena jsou samozřejmost.', '', '', 'Eliška – blond Praha, tety a křivky, sexy✨ TOP | LovelyGirls', '', '', '', 'Blondýnka s tetováním a přirozeným poprsím. Líbání, hluboký orál, foot fetish, role-play a lehké SM po dohodě; MŽM trojka bezpečně, diskrétně. Hygiena, hranice.', '', '', '', '', '', '', '', '', '', '', '', 'Křivky a ink, klidný žár na znamení 🪄', '', '', '');
